pipeline:
  - name: mastodon
    type: generate
    generate:
      output: mastodon.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: mastodon
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/fediverse/services/mastodon
          destination:
            server: https://kubernetes.default.svc
            namespace: mastodon
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true

  - name: matrix
    type: generate
    generate:
      output: matrix.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: matrix
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/fediverse/services/matrix
          destination:
            server: https://kubernetes.default.svc
            namespace: matrix
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true

  - name: mobilizon
    type: generate
    generate:
      output: mobilizon.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: mobilizon
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/fediverse/services/mobilizon
          destination:
            server: https://kubernetes.default.svc
            namespace: mobilizon
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true

  - name: pixelfed
    type: generate
    generate:
      output: pixelfed.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: pixelfed
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/fediverse/services/pixelfed
          destination:
            server: https://kubernetes.default.svc
            namespace: pixelfed
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
