apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  namespace: {{ .namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/harbor
        property: admin-password
    - secretKey: secretKey
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/harbor
        property: secret-key
