pipeline:
  - name: app-of-apps
    type: generate
    generate:
      output: app-of-apps.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: {{ .siteName }}-apps
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .siteName }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/{{ .siteName }}/apps
          destination:
            server: https://kubernetes.default.svc
            namespace: argocd
          syncPolicy:
            automated:
              prune: true
              selfHeal: true

  - name: service-apps
    type: generate
    generate:
      output: services.yaml
      template: |
        {{- range $i, $svc := .services }}
        {{- if $i }}
        ---
        {{ end -}}
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: {{ $.siteName }}-{{ $svc }}
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ $.siteName }}
          source:
            repoURL: {{ $.argocd.repoURL }}
            targetRevision: {{ $.argocd.targetRevision }}
            path: {{ $.argocd.basePath }}/{{ $.siteName }}/{{ $svc }}
          destination:
            server: https://kubernetes.default.svc
            namespace: {{ $svc }}
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
        {{- end }}
