apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: {{ .namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: minio-secrets
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/minio
        property: root-user
    - secretKey: rootPassword
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/minio
        property: root-password
