apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: {{ .namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: dex-secrets
    creationPolicy: Owner
  data:
    - secretKey: LDAP_BIND_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/dex
        property: ldap-bind-password
    {{- range .oidcClients }}
    {{- if has .service $.services }}
    - secretKey: OIDC_SECRET_{{ .service | upper }}
      remoteRef:
        key: {{ $.eso.remotePathPrefix }}/dex
        property: oidc-client-secret-{{ .service }}
    {{- end }}
    {{- end }}
