context:
  namespace: mastodon

pipeline:
  - name: render-templates
    type: template
    source:
      - file: kustomization.yaml
      - file: values.yaml
      - file: externalsecret.yaml
    template:
      files:
        include: ["**/*.yaml"]

  - name: build
    type: kustomize-build
    kustomize-build:
      enableHelm: true
      outputFile: kustomize-output.yaml

  - name: split-output
    type: split
    exclude: ["kustomize-output.yaml"]
    split:
      input: kustomize-output.yaml
      by: resource
      outputDir: manifests/
