pipeline:
  - name: ocis
    type: generate
    generate:
      output: ocis.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: ocis
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/office/services/ocis
          destination:
            server: https://kubernetes.default.svc
            namespace: ocis
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true

  - name: paperless
    type: generate
    generate:
      output: paperless.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: paperless
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/office/services/paperless
          destination:
            server: https://kubernetes.default.svc
            namespace: paperless
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true

  - name: stalwart
    type: generate
    generate:
      output: stalwart.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: stalwart
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/office/services/stalwart
          destination:
            server: https://kubernetes.default.svc
            namespace: stalwart
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
