apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stalwart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .argocd.project }}
  source:
    repoURL: {{ .argocd.repoURL }}
    targetRevision: {{ .argocd.targetRevision }}
    path: {{ .argocd.basePath }}/office/services/stalwart
  destination:
    server: https://kubernetes.default.svc
    namespace: stalwart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
