context:
  pg:
    appName: forgejo
    image: "postgres:16-alpine"
    dbName: forgejo
    dbUser: forgejo
    secretName: forgejo-secrets
    secretKey: POSTGRES_PASSWORD

pipeline:
  - name: render-templates
    type: template
    source:
      - file: manifests/
        path: manifests/
      - file: ../../shared/postgres.yaml
        path: manifests/
    template:
      files:
        include: ["**/*.yaml"]

  - name: create-kustomization
    type: kustomize-create
    kustomize-create:
      autodetect: true
      recursive: true
      namespace: forgejo
