pipeline:
  - name: render-templates
    type: template
    source:
      file: manifests/
      path: manifests/
    template:
      files:
        include: ["**/*.yaml"]

  - name: create-kustomization
    type: kustomize-create
    kustomize-create:
      autodetect: true
      recursive: true
      namespace: lldap
