apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .eso.secretStoreName }}
spec:
  provider:
    # Configure your secret backend here.
    # Example: HashiCorp Vault
    vault:
      server: "https://vault.{{ .domain }}"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
