pipeline:
  - name: fetch-and-render
    type: template
    source:
      # renovate: datasource=github-releases depName=kubernetes-sigs/metrics-server
      https: "https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml"
      sha256: "f103539a54ed72efe66616afc74a8bfaed651703cb3918797599046af5617441"
    template:
      files:
        include: ["**/*.yaml"]
