pipeline:
  - name: forgejo
    type: generate
    generate:
      output: forgejo.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: forgejo
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/sdp/services/forgejo
          destination:
            server: https://kubernetes.default.svc
            namespace: forgejo
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true

  - name: harbor
    type: generate
    generate:
      output: harbor.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: harbor
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/sdp/services/harbor
          destination:
            server: https://kubernetes.default.svc
            namespace: harbor
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true

  - name: woodpecker
    type: generate
    generate:
      output: woodpecker.yaml
      template: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: woodpecker
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: {{ .argocd.project }}
          source:
            repoURL: {{ .argocd.repoURL }}
            targetRevision: {{ .argocd.targetRevision }}
            path: {{ .argocd.basePath }}/sdp/services/woodpecker
          destination:
            server: https://kubernetes.default.svc
            namespace: woodpecker
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
